### PR TITLE
Hiding API keys into . env file

### LINKED ISSUE #63: Exposed API Keys
Hello! Not sure if it is intentional but your API keys are exposed which poses significant security risks. Probably best to create a .env file to store those in. If it is intentional ignore this :)

### PR DESCRIPTION
**Pull request by mariannerv**
DO NOT FORGET TO REMOVE THE .ENV FILE FROM YOUR REPO AFTER THIS :D

used npm install dotenv for the .env file

pip install python-dotenv (in case you dont have it)

created the .env file

Looked for all the exposed keys in the code, added them to the .env file and called them correctly on the code.

fixes #63

### CODE REVIEW

**Review by manascb1344 — COMMENTED** [review]
In many more places in ML Directory API Keys are exposed, make sure to look into it!!

**Comment by manascb1344** [comment]
Also it would be nice if a .env.example file is created for reference

**Comment by mariannerv** [comment]
You're right I did not catch those! And I  can absolutely do that!

**Comment by mariannerv** [comment]
I've commited the changed :)

**Comment by manascb1344** [comment]
@mariannerv
Thanks for sorting this out! Really appreciate it

**Pull request merged**
